### ISSUE TITLE
iOS 7.0 support?

### ISSUE THREAD

**Issue by rcancro** [Smartling/ios-lqa-sdk#1]
Hello!!!

Our international team is really excited about this! Unfortunately our app still supports iOS7.0 and your podspec appears to require 8.0. Are you doing things that aren't available on iOS 7.0 or did you just pick 8.0 because 7.0 is old? My $.02 is given that some international countries don't necessarily always have the latest phone, it may make sense for you guys to support 7.0. Any chance that could happen? :)

Thank you!!
Ricky

**Comment by foo4u** [comment]
@rcancro we picked iOS 8 to better support Swift. We do have a build supporting iOS 7.0. More information coming shortly.

**Comment by foo4u** [comment]
@rcancro we released an update adding back iOS 7 support.
