### ISSUE TITLE
How to use context capture?

### ISSUE THREAD

**Issue by michaelpetrov** [Smartling/ios-lqa-sdk#4]
This might be a very simple question but I can't seem to figure out how to get the context capture mode working. I'm in the process of upgrading from the old context capture SDK (the one with the "Hi" floating button) to this new SDK.

The Smartling module seems to connect correctly to Smartling and pull strings from my project. However my app UI has no "Hi" button or any other button to capture context. Only my UI is visible. Is there supposed to be a context capture button that appears if I setup the module in context capture mode?

I also tried to build to device and just take screenshots using the home and lock buttons at the same time and the Smartling module did not seem to respond to that in any way.

Am I supposed to see any UI at app startup? Is there something wrong with this integration?

Here is the startup output of the module at startup (maybe `No packaged strings file at (null)` is suspicious?):
```
2017-06-05 17:45:04.897738 SmartlingTestApp[333:34804] [SL] Starting up Smartling v1.3.9
2017-06-05 17:45:04.897924 SmartlingTestApp[333:34804] [SL] Debug enabled
2017-06-05 17:45:04.898007 SmartlingTestApp[333:34804] [SL] Context Capture enabled
2017-06-05 17:45:04.904956 SmartlingTestApp[333:34804] [SL] No packaged strings file at (null)
2017-06-05 17:45:04.905086 SmartlingTestApp[333:34804] [SL] Project base locale en
2017-06-05 17:45:04.906919 SmartlingTestApp[333:34804] [SL] Found downloaded strings on device for locale zh_CN
.... then lots of strings are printed
```

Thanks in advance for the help!

**Comment by emilienh** [comment]
Hi Michael,
This new SDK does not display any UI, you only need to make a one-finger long press to trigger a screenshot. Then the screenshot and its attached strings will be available in your Smartling dashboard under _Image Context_. 
You will find more information about the Context Capture mode here: https://help.smartling.com/docs/mobile-context.
Please let me know if you have any questions!

**Comment by michaelpetrov** [comment]
Hi Emilien, thank you! That was super helpful and my test integration is now working successfully.
