### ISSUE TITLE
Don't use categories to implement -awakeFromNib

### ISSUE THREAD

**Issue by lilyball** [Smartling/ios-lqa-sdk#7]
By using categories to implement this method, you're going to have a problem if UIKit ever decides to implement this method themselves on these classes. At the very least you should use method swizzling, so you can call the original method (if it's implemented, which you'd have to test for).

**Comment by emilienh** [comment]
Thanks for your feedback.

**Comment by aphexcx** [comment]
Is the custom -awakeFromNib implementation only done for the context capture feature? In other words, if one doesn't use context capture, can one avoid the custom implementation?

**Comment by emilienh** [comment]
The custom implementation is needed for all features, sorry. By the way the latest version uses swizzling instead of category overload.

**Comment by aphexcx** [comment]
Whoa, thanks for making that change!

**Comment by emilienh** [comment]
No problem, thanks for pointing it out!
